name: rag-tag-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn
  - matplotlib
  - networkx
  - tqdm
  - pillow
  - ipywidgets
  - rdflib
  - spacy
  - pip:
      - requests>=2.31.0
      - pymupdf>=1.23.0
      - sentence-transformers>=2.2.0
      - faiss-cpu>=1.7.4
      - openai
      - rank-bm25
      - pyvis
      - datasets
      - transformers
      - accelerate
